### ISSUE TITLE
JsonConverter Write methods not implimented.

### ISSUE THREAD

**Issue by SykesJohn** [vivet/GoogleApi#365] opened 2023-08-23 15:00 UTC
I get this error when trying to return a RoutesDirectionsResponse.

System.NotImplementedException: The method or operation is not implemented.
   at GoogleApi.Entities.Common.Converters.StringSecondsTimeSpanJsonConverter.Write(Utf8JsonWriter writer, TimeSpan value, JsonSerializerOptions options)

Looking at the code I see a number of Write methods that are not implemented in JsonConverters.

**Comment by vivet** [comment] 2023-08-24 05:03
Not sure what you are trying, but doesn't seem like you are using the library directly. Are you doing your own serialization?
The write methods are not needed as the library never writes Json but only reads it.

**Comment by SykesJohn** [comment] 2023-08-24 11:22
In my application I need to return the results of a CalculateRoute call, so the returned object needs to be serialized.

I could try doing everything in the client web assembly, but I’ve had problems using the library in that capacity in the past.

**Comment by vivet** [comment] 2023-08-25 04:16
Seems duplicate of #364
I will also close this issue.

**Closed by vivet** 2023-08-25 04:16 UTC
