### ISSUE TITLE
Support new Places API

### ISSUE THREAD

**Issue by mfeingol** [vivet/GoogleApi#402] opened 2024-12-11 04:57 UTC
Google is deprecating the old Places API, apparently.

Thanks.

**Comment by vivet** [comment] 2024-12-14 05:51
Can you link to the place where you see it's being deprecated?

**Comment by vivet** [comment] 2024-12-14 06:07
I will close this issue, as it's pretty much duplicate of this: https://github.com/vivet/GoogleApi/issues/379
If you can comment on that instead with a link to the deprecation notice.

**Closed by vivet** 2024-12-14 06:07 UTC
