### ISSUE TITLE
JsonSerializationException : Error converting value "postal_code_prefix" to type 'GoogleApi.Entities.Common.Enums.LocationType'

### ISSUE THREAD

**Issue by jamesmundy** [vivet/GoogleApi#50] opened 2017-09-15 07:58 UTC
Really useful library, thanks for your work on it. I've just encountered this issue when searching for a place via a string, and then getting the full place details:

`await GooglePlaces.Details.QueryAsync(request);`
The PlaceId I am retrieving is: `EiQxMjkgVGF1bnRvbiBSZCwgTGVlLCBMb25kb24gU0UxMiwgVUs`

The exception stacktrace I get is:
```
Newtonsoft.Json.JsonSerializationException : Error converting value "postal_code_prefix" to type 'GoogleApi.Entities.Common.Enums.LocationType'. Path 'result.address_components[7].types[0]', line 43, position 44.
  ----> System.ArgumentException : Requested value 'postal_code_prefix' was not found.
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
```

**Comment by vivet** [comment] 2017-09-15 08:02
Ok thanks to reporting it.
I expect I will be able to make fix later today.
Can you post the request data that lead to that placeId, cause I believe
those references changes.

**Comment by vivet** [comment] 2017-09-15 10:53
It turns out i cold use your PlaceId. 
I just remembered that google might change these, but in this case it wasn't.

The issue is fixed.
I will push a Nuget package soon.

**Comment by vivet** [comment] 2017-09-15 11:29
Nuget package publushed v3.2.4
Will close the issue.

**Closed by vivet** 2017-09-15 11:29 UTC

**Comment by jamesmundy** [comment] 2017-09-19 06:59
Awesome, thanks so much!

**Comment by vivet** [comment] 2017-09-19 07:14
No problem.
Let me know if you have further issues.
