### ISSUE TITLE
Place type not found - Place Text Search

### ISSUE THREAD

**Issue by rsvaughn** [vivet/GoogleApi#68] opened 2017-12-07 14:31 UTC
I received the below error when running a GooglePlaces TextSearch

![image](https://user-images.githubusercontent.com/20600157/33719804-94f094d6-db27-11e7-854d-162f176e4fb0.png)

When I took the raw query url and ran it I received  the below json result and the place type for "Kippel Islands" returned "archipelago" as a place type.  I did not see this place type listed in the Google Places documentation here https://developers.google.com/places/supported_types#table1 nor did I see it in the source code under PlaceLocationType.cs or in SearchPlaceType.cs.  Since this is not in the Google list I am not sure if this is a bug for you or for Google but I did want to bring this to your attention.  

```json
{
   "html_attributions" : [],
   "results" : [
      {
         "formatted_address" : "422 Scenic Hwy, Rosslyn QLD 4703, Australia",
         "geometry" : {
            "location" : {
               "lat" : -23.170764,
               "lng" : 150.789462
            },
            "viewport" : {
               "northeast" : {
                  "lat" : -23.1692183197085,
                  "lng" : 150.7908517802915
               },
               "southwest" : {
                  "lat" : -23.1719162802915,
                  "lng" : 150.7881538197085
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
         "id" : "56e230c8281a5f73fc7af328bd172276e6c3a41e",
         "name" : "Great Keppel Island Security Carpark",
         "place_id" : "ChIJT75mX7jowmsREWtTFKft68I",
         "reference" : "CmRSAAAAzGEoKySUuVbrDa6RF7_lIMKbV7idMz_wx6G16Z8_BuzMcS3QzrBv7Z9oVVZOrGdb0TTZ2kWts7rGRpFSg_EqqveVpKO9jRjYbMdXKcZ9d06Cxakw0k31eTJajfMB5FSMEhAJAwcTujtyD9wYpbD-yi6XGhSWdT8exuLrR-_mrIR63wLHS5gB4w",
         "types" : [ "parking", "point_of_interest", "establishment" ]
      },
      {
         "formatted_address" : "Kippel Islands, The Keppels QLD 4700, Australia",
         "geometry" : {
            "location" : {
               "lat" : -23.1238609,
               "lng" : 150.9773282
            },
            "viewport" : {
               "northeast" : {
                  "lat" : -23.0255836,
                  "lng" : 151.0937206
               },
               "southwest" : {
                  "lat" : -23.2221382,
                  "lng" : 150.8609358
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
         "id" : "f00c5c3f175778691a4658a083618b2e548b0e51",
         "name" : "Kippel Islands",
         "place_id" : "ChIJE6LOUCiVwmsRdE8rZVhsaTE",
         "reference" : "CmRbAAAAJpdXVffaZIiVW4F2qysJnzuxpG9G0Ro8mNHuYJzFLzthZ3qw7SdNgEHbtj4AuDHHW0R4IupCPmzKj3kM3yk5nK65y1mgWnhW-05VQ1CXp1sHndia4yVwwfjY3ow8B1IqEhDCYYew_iC0RmcpESG4lrRbGhRWht9fmNHoALfCwOrPax5Ha0fa2A",
         "types" : [ "archipelago", "natural_feature", "establishment" ]
      },
      {
         "formatted_address" : "The Esplanade, Great Keppel Island QLD 4703, Australia",
         "geometry" : {
            "location" : {
               "lat" : -23.17872599999999,
               "lng" : 150.93353
            },
            "viewport" : {
               "northeast" : {
                  "lat" : -23.17737701970849,
                  "lng" : 150.9348789802915
               },
               "southwest" : {
                  "lat" : -23.1800749802915,
                  "lng" : 150.9321810197085
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png",
         "id" : "0adfede43599267d7df63d076231a5e87244135b",
         "name" : "Great Keppel Island Hideaway",
         "opening_hours" : {
            "open_now" : false,
            "weekday_text" : []
         },
         "photos" : [
            {
               "height" : 657,
               "html_attributions" : [
                  "\u003ca href=\"https://maps.google.com/maps/contrib/111980555853980672916/photos\"\u003eGreat Keppel Island Hideaway\u003c/a\u003e"
               ],
               "photo_reference" : "CmRaAAAAVuXvoXEoDK2gLnG5Bnigc5z0s3IG4_l5_lMSxDvfex8oEeLU73nx-aHFgljBZj68LKFqzipgYp4GgavJEVCtyFDHZQm6nvmJT0S7hCwkGf1W7qmXmJBP72RKUkC1sHNDEhDrKx-tjd85K8rEzKHyeQbkGhTLvRQQKs5HKgQvwvhYAOtKemvW6g",
               "width" : 1027
            }
         ],
         "place_id" : "ChIJGTmmhiLrwmsRv8goXhzLNPw",
         "rating" : 4.2,
         "reference" : "CmRSAAAA1pDRHVwNR7pugGd2XpvUdqNVrq8AwHeiaf_k-rldmyQeC9HYSlethPTFEZqT-e5RUbRPAYKpFATQM48wTD41XuitZdJqhkqdQnW3VKGhcPU5hLIK59cIwaXPJDJ5Q4ZcEhA5n9dyGCacG1gQN-c72su5GhTWm0gRukcAQKfHGU8MCLtt2o5qpA",
         "types" : [
            "bar",
            "lodging",
            "restaurant",
            "food",
            "point_of_interest",
            "establishment"
         ]
      },
```

**Comment by vivet** [comment] 2017-12-08 14:03
I will go through the deserialization of these types with customer serializer, setting uknown enum value.

**Comment by vivet** [comment] 2017-12-09 09:14
New Nuget package v3.2.13 published.

**Comment by vivet** [comment] 2017-12-10 00:56
Please close the issue if the issue is solved for you.
NOTE: I chose not to add the non-documented place type. I don't think the information would be that important to anyone, but let me know if i am wrong.

**Closed** 2017-12-10 00:58 UTC
