### ISSUE TITLE
Nuget package cannot install on portable class libraries

### ISSUE THREAD

**Issue by APinheiroPT** [vivet/GoogleApi#31] opened 2017-06-07 15:07 UTC
This project is very useful for xamarin mobile applications, but can not install this in portable classes libraries, you can install this on Android Project and iOS project but not in the portable class library. The .dll is not added.

**Comment by vivet** [comment] 2017-06-08 09:29
From what I understand you seem to be using netcore, or am I wrong?
In that case I have built for netstandard, which doesn't worry about
portable libraries.
Enlighten me if I am mistaken.

**Comment by APinheiroPT** [comment] 2017-06-08 09:45
No, i'm not using netcore, i'm using xamarin.forms, if you want i will send you a small example for you see.

**Comment by sirfilipef** [comment] 2017-06-08 09:56
The problem is that if you install it in the Xamarin Forms, for example target: portable-net45+win8, the library just installs on Xamarin.iOS and Xamarin.Android and doesnt install on Xamarin portable project. And if you force to add .dll .netstandard to the project portable, there is a bug with "Mono.Posix" in the debbuger.

https://gyazo.com/6a07092d42edd8030bd861b520dc9944

I think there are something in the library that trows this error.

**Comment by vivet** [comment] 2017-06-08 10:02
Yes it's as I expected.
I haven't built for that, though wonder why you are able to add it then. I
have only built for .netstandard 1.3 and .net4.5

**Comment by sirfilipef** [comment] 2017-06-08 10:04
I think there is a compatility between .netstandard 1.3 and portable-net45+win8 (profile7)

**Comment by vivet** [comment] 2017-06-08 10:09
I cant remember, but i think that is 1.2
No matter, i planned to fix another issue today and publish a new nuget. I will look into adding a built for your need, though I can't promise it will work if 'portable-net45+win8 (profile7)' isn't compatible with netstandard1.3

**Comment by sirfilipef** [comment] 2017-06-08 10:13
OK. Thank you.

**Comment by vivet** [comment] 2017-06-08 19:23
Hi

I checked the exception in your screenshot, and unfortunately it doesn't tell me much, as I haven't consumed using Xamarin.

I have added a portable project to the solution and when building, I get errors for netstandard1.3 namespace references. So it pretty much confirms my initial comment about compatibility.

nevertheless, I am trying to get the solution downgraded to netstandard1.2, which should make it work for you. Though before publishing a new nuget i will send the assembly so you can confirm it works

**Comment by vivet** [comment] 2017-06-08 20:10
I have made a build for netstandard1.2. 
If you can try that built and see if it works for you. You will need to add Nuget package for 'Portable.BouncyCastle'. I have added the dll here: https://github.com/vivet/GoogleApi/blob/ISSUE_31/GoogleApi/GoogleApi.dll 

Let me know if it works, and i will publish an updated Nuget package

**Comment by sirfilipef** [comment] 2017-06-14 09:22
I tracked the issue here, I thing this is a problem with Xamarin Platform, and doesn't have anything with your library
[link](https://bugzilla.xamarin.com/show_bug.cgi?id=56787)
I will try your updated nuget, and let you know if the library installs in the project

**Comment by vivet** [comment] 2017-06-14 09:26
Hi

Yes i think you are right, i reproduced the same error as you linked to.
I believe the change i made in the dll attached to the issue should make it
work.

When you say updated nuget you refer to the dll i attached right? Cause the
public nuget isn't updated yet.

**Comment by sirfilipef** [comment] 2017-06-14 09:32
Discarding the Xamarin's Posix problem, another issue was that the actual nuget doesn't install on the portable library, but if I added the dll manually works.
Could this be a problem with the nuspec?

Possible example:

` <file src="bin\Release\library.dll" target="lib\portable-net45+wp8+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+UAP10\library.dll" />`

**Comment by vivet** [comment] 2017-06-14 09:43
Hi

The actual nuget is netstandard1.3 and not portable.
When it works i can add the build for netstandard1.2 which should work, or
if not directly as the portable library.

**Comment by vivet** [comment] 2017-06-20 19:47
Hello. Hope you are doing well.
Have you had a chance to try the dll i made?

**Comment by vivet** [comment] 2017-06-21 10:49
Hi again,
I didn't see your comment about "actual nuget doesn't install on the portable project".
That is true, cause i haven't made a build for that specific netcore portable library. The reason is that netcore is obsolete, taken over by netstandard. Different version of netstandard is supported on different platforms. The dll i made for you is lowered to netstandard1.2 where as it was 1.3 before. That should make it work for your platform, which we need to determine first. Later, i can add the nuspec if needed.

Makes sense?

**Comment by vivet** [comment] 2017-06-23 18:13
Hi 
I will close the issue.
Feel free to re-open or contact me if you still have issues.
Just so you know, I am working on a v3.0, where i permanently will downgrade to netstandard1.2, but if that still doesn't work i will add the portable Nuget, just let me know. Just want your confirmation that the dll works, before i publish an update on Nuget.

Have a nice weekend.

**Comment by vivet** [comment] 2017-07-20 16:33
I have experimented more with the problem, and in the end i think you are right. 
Netstandard1.x doesn't work. 

I have just released v3.0, and I am adding a portable package as well.

**Comment by vivet** [comment] 2017-07-20 17:11
I just published Nuget with the package i believe you need.
All though i also downgraded the general package to netstandard1.1, which according to this page (https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) should be compatible with your application. 

Let me know how it goes, and otherwise if you still experience issues, I will work on a solution with you.

**Closed** 2017-07-21 14:15 UTC
