### ISSUE TITLE
Using PageToken for next 20 results returns error

### ISSUE THREAD

**Issue by ChuckHoffSki** [vivet/GoogleApi#131] opened 2018-09-14 09:42 UTC
Hi

I'm using the code below to return multiples of 20 based on a user selection.
The initial request returns data fine, but all requests after that when I try to use the NextPageToken from the server result in the next query fail with an "Invalid Request" Exception.

            PlacesNearbySearchResponse ServerResult;

            PlacesNearBySearchRequest TheSearchQuery = new GoogleApi.Entities.Places.Search.NearBy.Request.PlacesNearBySearchRequest()
            {
                Location = new GoogleApi.Entities.Common.Location (MainMap.Position.Lat,MainMap.Position.Lng),
                Radius = (float)(1.0 * MapHighlightedArea.Radius * 50000 / 0.5),
                Key = OT3Reports.ReportGlobals.GoogleAPIKey
            };

                // add first batch of results
                List<NearByResult> TempGoogleResults = ServerResult.Results.ToList();
                // Do all the next pages.
                string NextPageTokenTemp = ServerResult.NextPageToken;

                int i = 0; // iterator for # of results
                while ((NextPageTokenTemp != null) && (i <= comboBoxEditResults.SelectedIndex))
                {
                    TheSearchQuery.PageToken = NextPageTokenTemp;

                    ServerResult = GoogleApi.GooglePlaces.NearBySearch.Query(TheSearchQuery);

                    // add next batch of results;
                    TempGoogleResults.AddRange(ServerResult.Results.ToList());
                    // Assign next Token
                    NextPageTokenTemp = ServerResult.NextPageToken;
                    // advance the counter 
                    i++;
                }

**Comment by vivet** [comment] 2018-09-14 11:18
Hi
I will check it out.

**Comment by vivet** [comment] 2018-09-14 17:32
Also another thing to mention is that the ```GoogleApiExpcetion``` contains the error message from google, which in this case is empty. To me it indicates that Google has changed something. They did recently make greater changes to places search.

**Comment by ChuckHoffSki** [comment] 2018-09-17 07:15
Hi,
I've noticed that if I change the Rankby parameter to Distance then the Pagetokens work as expected.

Its odd that this doesn't work for RankBy=Prominence  as this is the default setting, but this seems like a google issue and I can get around it for now by using distance.

thanks for your help.

**Comment by vivet** [comment] 2018-09-17 07:17
Hi
Nice that you found a workaround. I too think this is a google issue.

Please star my library if you like it 😃

Can I close the issue?

**Comment by ChuckHoffSki** [comment] 2018-09-17 07:18
yes, thanks again fro your help

**Comment by aeoriwnd** [comment] 2020-01-14 14:28
This issue still persists. The problem is when there is PageToken, there is no need to specify any other parameters, but your classes are restiricted to always have Location and other fields.  Those fields should **not** be present when tehre is pagetoken

**Comment by vivet** [comment] 2020-01-14 14:36
Will check it tomorrow

**Comment by vivet** [comment] 2020-01-15 08:42
I have implemented the change, so now Text and NearBy search will only pass the key and pagetoken, if  a pagetoken is set.

Check out the PR: https://github.com/vivet/GoogleApi/pull/181

I will merge later today.

**Comment by viticush** [comment] 2020-02-11 14:53
Hi @vivet I have same problem wit TextSearch response, in some cases it returns Invalid request, Can you check like nearby search?

Thanks in advance!

**Comment by vivet** [comment] 2020-02-11 16:49
Will see if I can reproduce that. Otherwise try to consult the Googlele docs

**Comment by vivet** [comment] 2020-02-12 12:41
Could it be that the original request isn't valid for using nextpagetoken?

**Comment by vivet** [comment] 2020-02-15 13:21
I have done some testing, and I can confirm that i too get "Invalid Request". It seems quite random and mostly i works as it should. The code seems fine as well, so I honestly don't know why this is happening. I have implemented a test, that proves it works. If you can provide me with the query that fails for you I can try using that.

**Comment by vivet** [comment] 2020-02-18 08:57
Since I haven't heard back, I will close the issue

**Closed** 2020-02-18 08:58 UTC

**Comment by viticush** [comment] 2020-02-18 09:20
Sorry I can't answer you these days, the request that I used should be like:

https://maps.googleapis.com/maps/api/place/textsearch/json?input=lake%20in%20CA&inputtype=textquery&key=API_KEY

my code it is like this:

                    request.Query = textToSearch.ToLower() + " in CA";
                    request.Key = myKey;
                    request.Language = GoogleApi.Entities.Common.Enums.Language.English;
                    request.PageToken = null;

                    List<TextResult> results = new List<TextResult>();
                    PlacesTextSearchResponse response = 
                    GoogleApi.GooglePlaces.TextSearch.Query(request);
                    if (response.Results.Count() > 0)
                    {
                        while (response.NextPageToken != null)
                        {
                            results.AddRange(response.Results);

                            request.PageToken = response.NextPageToken;

                            response = GoogleApi.GooglePlaces.TextSearch.Query(request);
                        }
                        results.AddRange(response.Results);
                    }
Using while section (or changing to a if) I had the same issue, maybe it is because the petition is too fast and Google cannot allow multiple petitions.

**Comment by vivet** [comment] 2020-02-19 09:10
I think you are right about that. I get the same error when executing multiple tests for either nearby or text search.

**Comment by rssllgrrtt** [comment] 2020-10-31 16:00
I've run into this problem as well. As @viticush says, the exception is thrown in my while loop. My solution was to just create an artificial delay for a few seconds with a simple Task.Delay.

The problem won't ever occur if I debug my application. It'll only happen in production. My assumption is that debugging it slows the process down enough.
