### ISSUE TITLE
JsonSerializationException: A member with the name 'time' already exists on 'GoogleApi.Entities.Places.Details.Response.Review'. 

### ISSUE THREAD

**Issue by jamesmundy** [vivet/GoogleApi#91] opened 2018-03-16 17:25 UTC
Just ran into another JsonSerializationException:

```"A member with the name 'time' already exists on 'GoogleApi.Entities.Places.Details.Response.Review'. Use the JsonPropertyAttribute to specify another name."```

I got this error while trying to retrieve the details of the PlaceID (ChIJ6cgcFbDGdkgRw-yWvDgYQTQ).

**Comment by vivet** [comment] 2018-03-16 17:33
Hi
I will take a look at it.

**Comment by vivet** [comment] 2018-03-17 05:46
Hi
I couldn't reproduce the problem. I tried your PlaceId, and i get 5 reviews all serialized correctly.
No matter, the problem should be two properties named "time". So i renamed the public one, and i believe it should fix your issue.

If you can try out the branch, then after your confirmation i will publish a NuGet update.

**Comment by jamesmundy** [comment] 2018-03-17 13:00
Thanks @vivet, will try now.

**Comment by jamesmundy** [comment] 2018-03-17 13:11
Yep @vivet that works now, thanks!

**Comment by vivet** [comment] 2018-03-17 15:48
Ok cool
O will publish a new NuGet package.

**Comment by vivet** [comment] 2018-03-17 15:56
It's published just now.
Please close the issue when you have confirmed.

**Comment by vivet** [comment] 2018-03-23 02:57
Will close the issue.
Hope its resolved.

**Closed by vivet** 2018-03-23 02:57 UTC
Labels: bug
