### ISSUE TITLE
Error converting value "ZERO_RESULTS" to type 'GoogleApi.Entities.Common.Enums.Status'.

### ISSUE THREAD

**Issue by belacicg** [vivet/GoogleApi#109] opened 2018-07-09 13:57 UTC
I want to draw route using xamarin forms & create request like this:
var request = new DirectionsRequest
            {
                Key = AppSettings.GoogleApiKey,
                Origin = origin,
                Destination = dest,
                TravelMode = mode
            };
After that when I want go get directions:
 var response = await GoogleMaps.Directions.QueryAsync(request);

I got exception:
GoogleApi.Exceptions.GoogleApiException: Error converting value "ZERO_RESULTS" to type 'GoogleApi.Entities.Common.Enums.Status'. Path 'geocoded_waypoints[0].geocoder_status',

This is happening only on Android version 6.0.1. 
On Android 7.0 and iOS works fine.

**Comment by vivet** [comment] 2018-07-09 14:18
Hi
That's strange. I see no reason why that should be different. Basically, it should be able to deserialize the value, ad you can see here: 
https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Common/Enums/Status.cs

Honestly, I am puzzled how that can differ...

**Comment by vivet** [comment] 2018-07-09 14:21
I will implement to ignore this error.

**Comment by vivet** [comment] 2018-07-10 21:02
Hi
I have changed to ignore errors for the status enum that failed for you.
I will publish NuGet package within the hour.

Let me know how it works out, or if you are still experiencing issues. 
If it works, try inspect the ```response.RawJson```, and see the actual value (paste the json here, and i will check it).
If it still doesn't work, paste you full request so i can try reproducing the error.

**Comment by belacicg** [comment] 2018-07-12 11:00
Nuget update is still not available.

**Comment by vivet** [comment] 2018-07-12 11:01
Hi
Was just about to write to you :-)
Will check it right away

**Comment by vivet** [comment] 2018-07-12 11:03
ahhh I accidentally published it to my private NuGet feed.
WIll publish now

**Comment by vivet** [comment] 2018-07-12 11:12
It's validating now, and should be available shortly.
Also, please star my project if you like it.

Let me know how the fix works out for you, and i am also still interested in, what the actual value in the response is (that gives issues).

**Comment by belacicg** [comment] 2018-07-12 14:03
No luck after nuget update.
Same error.

Unhandled Exception:
GoogleApi.Exceptions.GoogleApiException: Error converting value "ZERO_RESULTS" to type 'GoogleApi.Entities.Common.Enums.Status'. Path 'geocoded_waypoints[0].geocoder_status', line 4, position 43. occurred

**Comment by vivet** [comment] 2018-07-12 14:04
Hmm...
Can you give me the request you are trying. I will need to try reproduce it

**Comment by vivet** [comment] 2018-07-12 14:05
...and also if you able to extract the RawJson from the ```ex.Response.RawJson``´, so we can see how the json actually looks.

**Comment by vivet** [comment] 2018-07-16 08:09
Hi
Any update ?

**Comment by vivet** [comment] 2018-07-18 15:59
I will close the issue.
I can't reproduce it. 

Feel free to re-open if you get the response

**Closed by vivet** 2018-07-18 15:59 UTC
