### ISSUE TITLE
Make DistanceMatrixRequest.TrafficModel nullable.

### ISSUE THREAD

**Issue by yzhogoliev** [vivet/GoogleApi#121] opened 2018-07-30 10:56 UTC
The request with the explicitly provided "traffic_mode" value, requires the "departure_time" parameter to be provided as well.
Error message: "Invalid request. Missing the 'departure_time' parameter."

It would be ok, to provide "departure_time=now", as a fix, but the library doesn't support this special value.

**Comment by vivet** [comment] 2018-07-31 04:49
Hi
I recently made the change, but I can see that was a mistake.
I will revert it, and allow traffic model to be null.

**Comment by yzhogoliev** [comment] 2018-07-31 06:17
No problem 👍 . According to the description of the API, it should work, but it doesn't.

**Comment by vivet** [comment] 2018-07-31 18:12
I have improved the implementation further and published and updated NuGet package.
Let me know if you still experience issues.

**Comment by vivet** [comment] 2018-07-31 18:12
You can check this commit.
https://github.com/vivet/GoogleApi/commit/1eb0c1c4b26274410e84c2fe29765180ecedd438

**Comment by vivet** [comment] 2018-08-01 13:52
I will close the issue.
Let me know if you still are having issues.

Also please star my library if you like it.

**Comment by yzhogoliev** [comment] 2018-08-09 18:02
@vivet We should re-open this issue,
According to the description of the API (https://developers.google.com/maps/documentation/distance-matrix/intro) - the default `traffic_model` is `best_guess` and the default `departure_time` in this case is `now`, but if you try to provide the same values to the API it takes a much longer time to get a result and commonly fails (500 error). If you don't provide any - everything is ok - requests are really fast.

**Comment by vivet** [comment] 2018-08-09 19:34
Hi
Seems strange that it behaves like that. I would think default values should produce the same result.
Anyhow, I will look into it tomorrow.

**Comment by vivet** [comment] 2018-08-11 06:31
Hi
I am sorry but I didn't have any time yesterday, and my weekend I completely booked, so I won't be able to look at the issue before Monday / Tuesday.

**Comment by vivet** [comment] 2018-08-17 06:15
Hi news?

**Comment by yzhogoliev** [comment] 2018-08-18 15:33
Hi, possibly it was some issue on the google's end at the moment because I can't reproduce the issue now.

**Comment by yzhogoliev** [comment] 2018-08-18 15:34
Anyway, it's better to have an option to skip default parameters in the request.

**Comment by vivet** [comment] 2018-08-19 06:26
Hi
Okay, glad the issue is resolved for you.
I don't fully agree with skipping the default parameters. I understand the point of view, but generally throughout the api-client I have tried to default as much as possible, in order to ease the use.

**Comment by vivet** [comment] 2018-08-22 17:26
I will close the issue.

**Closed by vivet** 2018-08-22 17:26 UTC
