### ISSUE TITLE
Places auto complete bug

### ISSUE THREAD

**Issue by Michael-Kyriacou** [vivet/GoogleApi#77] opened 2018-02-04 10:27 UTC
Hello,

I tried auto complete for 'Places' and it works great. The issue is, when I try to filter by 'Cities', google returns:
predictions | []
-- | --
status | "INVALID_REQUEST"

I checked the exception I got, and the request url is like this:

https://maps.googleapis.com/maps/api/place/autocomplete/json?key=[MY_API_KEY]&sensor=false&input=Nic&language=en&types=cities

If I try to run it on my browser like this:

https://maps.googleapis.com/maps/api/place/autocomplete/json?key=[MY_API_KEY]&sensor=false&input=Nic&language=en&types=(cities) 
it works fine.

For more info please check how I am constructing my query in C#:
```
var request = new PlacesAutoCompleteRequest
            {
                Key = apiKey,
                Input = input,
                Types = new List<RestrictPlaceType>() { RestrictPlaceType.Cities }
            };
```

And here is some info in the exception
![bug](https://user-images.githubusercontent.com/5446409/35776522-c4f63af2-09a6-11e8-8bed-70eb755e5f0e.png)
Thanks.

**Comment by vivet** [comment] 2018-02-04 13:54
Hi
I will look into the issue, and see if i can reproduce it.
Thanks for reporting it

**Comment by vivet** [comment] 2018-02-05 17:59
Hi 
I found the issue. Turns out for the types "Regions" and "cities", Google expects parentheses around the type name. I am implementing the fix

**Comment by vivet** [comment] 2018-02-05 18:07
The issue is fixed.
I will push a Nuget after i fix issue #78

**Comment by vivet** [comment] 2018-02-05 18:22
I will publish Nuget now.
Please close the issue when confirmed, and also if you like the project please give it a star.

**Comment by Michael-Kyriacou** [comment] 2018-02-05 22:16
Yes it works fine! 

Thank you so much.

**Closed** 2018-02-05 22:16 UTC
Labels: bug
